### ISSUE TITLE
Vectorize implementation of prob_for_vars using NumPy

### ISSUE THREAD

**Issue by AnthonyWeston** [svohr/mixemt#11]
I tried this software out once, and it took a long time to process. I used cProfile to profile the application, and my results indicated that it spends most of its time computing logs. I would like to vectorize the implementation of prob_for_vars using NumPy. I don't have access to the dataset I used before, so can anyone provide a sample dataset I can use to benchmark the performance of the application before and after implementing this?

**Comment by svohr** [comment]
Terrific! I agree that the process of scanning the input reads and building the initial fragment/haplogroup matrix is quite slow and that there's room for improvement. The original rationale for the way [HapVarBaseMatrix](https://github.com/svohr/mixemt/blob/master/mixemt/preprocess.py#L23) is implemented was to avoid building the complete 3-dimensional matrix of A,C,G,T x variant positions x haplogroup and keeping it in memory when most cells are uninformative. I've been curious to see what type of improvement we might see by implementing this step with vector operations.

I will see about adding an example bam file of alignments to the repository for benchmarks. It would be a good thing to have in general. Thanks!

**Comment by AnthonyWeston** [comment]
The log computations took < 1/2 of the total computation time for me. It seemed that _prob took the most total computation time, but since it's just a series of dictionary lookups I'm not sure we could speed that up much, although I think it could be reduced from four dictionary lookups to 3, but I would like to test whether that actually improves performance. Besides that, I could see parallelizing the filling of read_hap_mat in build_em_matrix being a great help.

**Comment by alexhbnr** [comment]
Hi @svohr and @AnthonyWeston,

I have had similar problems with the computation time and took some measures to reduce the run time by enabling the parallel execution of the code. The two functions for which I implemented a parallel execution are `build_em_matrix` and `em_step`:

1. `build_em_matrix`

It uses the function `map` from the module `multiprocessing` in order to fill the initial EM matrix in parallel. The chunk size is chosen that one worker subprocess iterates over all haplogroups for one read. Therefore, the number of threads available determine how many reads are processed in parallel.

2. `em_step`

Here, the most expensive function was `logsumexp` from Scipy, which was particularly slow for large matrices with a lot of input reads. I implemented a 1:1 translation of the code for Numba, a JIT compiler, which enables parallel execution.

I have not done proper benchmarking, but the sample can be processed in a fraction of the time of the original, non-parallel implementation.

I updated the version to run on Python3 and have parallel execution enabled by default, with the option to switch it off and return to original code as a fallback (see pull request #21). Except for parallelization and remove the multiple dictionary look-up mentioned above, I did not change the algorithm, so one should expect similar results, give or take the uncertainty of the EM result.
