### ISSUE TITLE
Getting error zero-size array to reduction operation maximum which has no identity using default settings.

### ISSUE THREAD

**Issue by aminards** [svohr/mixemt#9]
I am trying to run mixemt on a filtered .bam file using default settings.  I am getting the following error:

``[smitha@ls-hpchead01 ~]$ mixemt /hpc/home/smitha/Mixtures/mtDNA_MixRun2/mtDNA_MixRun2_sort_filtered.bam
          
[fai_load] build FASTA index.

Error:
 zero-size array to reduction operation maximum which has no identity
``

Since this error message does not come with any other information I do not know where to find the problem or what is causing the problem.  Any suggestions?

**Comment by svohr** [comment]
Thanks for posting this issue. My guess is that there are no alignments found, which could be due to the default minimum mapping quality filter (default=30) or an empty bam file. You can set minimum mapping quality with the `-q` flag (e.g., `-q 0` to use all alignments in the bam file). If you still see this problem, could you run mixemt again with the `-v` option to see where this error is occurring?

**Comment by aminards** [comment]
You were absolutely correct on the -q issue.  I added -q 0 and -Q 5 just to be safe and everything seems to be running as expected.  Thank you very much.

**Comment by svohr** [comment]
Great! In general, I would recommend setting your minimum map quality and minimum base quality settings as high as possible given your data. MAPQ >= 0 is too low for most cases, but if you trust your alignments or your aligner does not use the MAPQ field it may be fine.

Thanks again for submitting this. I will add a check for an empty set of input alignments and an error message to mixemt.
